#!/usr/bin/env php
<?php
/**
 * Yii console bootstrap file.
 *
 * @link http://www.yiiframework.com/
 * @copyright Copyright (c) 2008 Yii Software LLC
 * @license http://www.yiiframework.com/license/
 */


require(__DIR__ . '/vendor/autoload.php');
require(__DIR__ . '/env.php');
require(__DIR__ . '/vendor/yiisoft/yii2/Yii.php');

$config = require(__DIR__ . '/config/console.php');
// debug tools
function d()
{
    foreach (func_get_args() as $val) {
        var_dump($val);
    }
}

function dx()
{
    foreach (func_get_args() as $val) {
        d($val);
    }
    exit;
}

$application = new yii\console\Application($config);
$exitCode = $application->run();
exit($exitCode);
